---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes
- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0

- name: "Install pm2 Globally"
  npm:
    name: pm2
    global: yes