---
- name: Add NodeJs from node source
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_10.x sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0
    
- name: Install NodeJs 10.x
  become: true
  apt: 
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: Install PM2 Globally
  npm:  
    name: pm2
    global: yes