---
- name: "Create back-end directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive back-end files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install nodejs deps"
  shell: |
    cd ~/backend-app
    npm i

- name: "Execute nodejs app using PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save