---
- name: "create backend app directory"
  become: true
  file:
    path: /home/circleci/project/backend
    state: directory

- name: "unarchive backend files"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/circleci/project/backend

- name: "install node dep"
  become: true
  shell: |
    cd /home/circleci/project/backend
    npm install
- name: "executing node app with PM2"
  become: true
  shell: |
    cd /home/circleci/project/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: "print message"
  become: true
  debug:
    msg: "{{execute_node.stdout_lines}}"

- name: "configure pm2 start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu